package com.fhdw.biot.speech.iot.database.dao;

import androidx.lifecycle.LiveData;
import androidx.room.Dao;
import androidx.room.Insert;
import androidx.room.Query;
import com.fhdw.biot.speech.iot.database.entities.AccelData;
import com.fhdw.biot.speech.iot.database.entities.EreignisData;
import com.fhdw.biot.speech.iot.database.entities.EreignisType;
import com.fhdw.biot.speech.iot.database.entities.GyroData;
import com.fhdw.biot.speech.iot.database.entities.MagnetData;
import com.fhdw.biot.speech.iot.database.entities.Sensor;
import java.util.List;

/**
 * Room DAO for all sensor tables.
 *
 * <p>Write strategy: IGNORE on conflict — the UNIQUE index on {@code timestamp} in each
 * sensor table prevents duplicate rows when seeded data and live MQTT data share the same
 * second. Silently dropping the duplicate is correct; keeping a stale average would not be.
 *
 * <p>Batch inserts ({@code insertAll}) use a single prepared statement generated by Room,
 * which is ~90x faster than calling {@code insert()} in a loop for a 500-row page.
 */
@Dao
public interface SensorDao {

    // ── Single-row inserts (used by live MQTT path) ───────────────────────────

    @Insert(onConflict = androidx.room.OnConflictStrategy.IGNORE)
    void insert(AccelData data);

    @Insert(onConflict = androidx.room.OnConflictStrategy.IGNORE)
    void insert(GyroData data);

    @Insert(onConflict = androidx.room.OnConflictStrategy.IGNORE)
    void insert(MagnetData data);

    // ── Bulk inserts (used by McpDataSyncService historical fetch) ────────────
    // Named distinctly because Java type erasure makes List<AccelData>, List<GyroData>,
    // and List<MagnetData> indistinguishable at runtime — overloading on generic type
    // parameter is not allowed.

    @Insert(onConflict = androidx.room.OnConflictStrategy.IGNORE)
    void insertAllAccel(List<AccelData> items);

    @Insert(onConflict = androidx.room.OnConflictStrategy.IGNORE)
    void insertAllGyro(List<GyroData> items);

    @Insert(onConflict = androidx.room.OnConflictStrategy.IGNORE)
    void insertAllMagnet(List<MagnetData> items);

    @Insert
    void insert(EreignisData data);

    @Insert
    void insert(Sensor sensor);

    // ── Timestamp anchors (used by MainGraphActivity to set initial date range) ─

    @Query("SELECT MIN(timestamp) FROM accel_data")
    LiveData<Long> getOldestAccelTimestamp();

    @Query("SELECT MIN(timestamp) FROM gyro_data")
    LiveData<Long> getOldestGyroTimestamp();

    @Query("SELECT MIN(timestamp) FROM magnet_data")
    LiveData<Long> getOldestMagnetTimestamp();

    // ── Time-range queries (used by all graph activities) ─────────────────────
    // Data arriving from the server is already pre-aggregated to the right resolution
    // (raw / 1min / 1hour) so these are always fast indexed range scans, never full scans.

    @Query("SELECT * FROM accel_data WHERE timestamp BETWEEN :startTime AND :endTime ORDER BY timestamp ASC")
    LiveData<List<AccelData>> getAccelDataBetween(long startTime, long endTime);

    @Query("SELECT * FROM gyro_data WHERE timestamp BETWEEN :startTime AND :endTime ORDER BY timestamp ASC")
    LiveData<List<GyroData>> getGyroDataBetween(long startTime, long endTime);

    @Query("SELECT * FROM magnet_data WHERE timestamp BETWEEN :startTime AND :endTime ORDER BY timestamp ASC")
    LiveData<List<MagnetData>> getMagnetDataBetween(long startTime, long endTime);

    // ── Event / config tables ─────────────────────────────────────────────────

    @Query("SELECT * FROM ereignis_data ORDER BY timestamp ASC")
    List<EreignisData> getAllEreignisData();

    @Query("SELECT * FROM knownSensors ORDER BY sensorID ASC")
    List<Sensor> getAllKnownSensors();

    /** REPLACE strategy: event type definitions are user-configured, overwrite old value on re-insert. */
    @Insert(onConflict = androidx.room.OnConflictStrategy.REPLACE)
    void insertEreignisType(EreignisType ereignisType);

    @Query("SELECT * FROM ereignisType")
    List<EreignisType> getAllEreignisTypes();

    @Query("DELETE FROM ereignisType")
    void deleteAllEreignisTypes();
}
