package com.fhdw.biot.speech.iot.config;

import com.fhdw.biot.speech.iot.BuildConfig;

import java.util.Locale;

/**
 * AppConfig
 * ─────────────────────────────────────────────────────────────────────────────
 * Centralised, runtime-immutable application configuration.
 *
 * Reads from {@link BuildConfig} which is generated by Gradle from the
 * {@code buildConfigField} entries in {@code app/build.gradle}. This keeps
 * the LAN IP, the LLM endpoint and the MQTT port out of source code so they
 * can be overridden per build variant or per developer machine without
 * touching .java files.
 *
 * Defaults (sensible for a fresh checkout):
 *   PHONE_BROKER_URL    = tcp://192.168.178.80:1883
 *   EMULATOR_BROKER_URL = tcp://10.0.2.2:1883
 *   LLM_HOST_PHONE      = 192.168.178.80
 *   LLM_HOST_EMULATOR   = 10.0.2.2
 *   LLM_PORT            = 8001
 *
 * Override in app/build.gradle, e.g.
 *   buildConfigField "String", "PHONE_BROKER_URL", '"tcp://192.168.0.42:1883"'
 *
 * Or per build type:
 *   buildTypes {
 *       debug   { buildConfigField "String", "LLM_HOST_PHONE", '"192.168.0.42"' }
 *       release { buildConfigField "String", "LLM_HOST_PHONE", '"biot.example.com"' }
 *   }
 */
public final class AppConfig {

    private AppConfig() {}

    // ─────────────────────────────────────────────────────────────────────────
    // Brokers
    // ─────────────────────────────────────────────────────────────────────────

    public static String mqttBrokerUrl() {
        return isEmulator() ? BuildConfig.EMULATOR_BROKER_URL : BuildConfig.PHONE_BROKER_URL;
    }

    // ─────────────────────────────────────────────────────────────────────────
    // LLM
    // ─────────────────────────────────────────────────────────────────────────

    /** Full URL of the BioT LLM_App's POST /chat endpoint. */
    public static String llmChatEndpoint() {
        String host = isEmulator() ? BuildConfig.LLM_HOST_EMULATOR : BuildConfig.LLM_HOST_PHONE;
        int port = BuildConfig.LLM_PORT;
        return "http://" + host + ":" + port + "/chat";
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Emulator detection — single source of truth (was duplicated in MainActivity)
    // ─────────────────────────────────────────────────────────────────────────

    public static boolean isEmulator() {
        String f = lower(android.os.Build.FINGERPRINT);
        String m = lower(android.os.Build.MODEL);
        String p = lower(android.os.Build.PRODUCT);
        return f.startsWith("generic")
                || f.contains("vbox")
                || f.contains("test-keys")
                || m.contains("google_sdk")
                || m.contains("emulator")
                || m.contains("android sdk built for x86")
                || p.contains("sdk_gphone");
    }

    private static String lower(String s) {
        return s == null ? "" : s.toLowerCase(Locale.US);
    }
}
